apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eval-results-pvc
  namespace: {{ include "rinlekha.namespace" . }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.evalJob.resultsStorage }}
