apiVersion: v1
kind: Secret
metadata:
  name: rinlekha-secrets
  namespace: {{ include "rinlekha.namespace" . }}
type: Opaque
stringData:
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
  hf-token: {{ .Values.secrets.hfToken | quote }}
